# Introducao ao Numpy

In [14]:
import numpy as np

In [6]:
#lista generica em python
lista_de_numeros = [1 , 2, 3, 4, 5]
lista_de_numeros[1] = 3
print(lista_de_numeros)

#Array do numpy criada a partir da lista anterior
array_numpy = np.array(lista_de_numeros)
print(array_numpy)

[1, 3, 3, 4, 5]
[1 3 3 4 5]


In [7]:
#Apesar de ambos serem listas o python considera a Array do numpy um tipo distinto
print(type(lista_de_numeros))
print(type(array_numpy))

<class 'list'>
<class 'numpy.ndarray'>


In [12]:
#Funcao pronta do numpy para criar uma lista de um numero especifico, onde a quantidade de numeros e usada como parametro 
lista_de_zeros = np.zeros(7)
lista_de_uns = np.ones(9)
print(lista_de_zeros)
print(lista_de_uns)

[0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [16]:
#Matrizes
matriz_de_zeros = np.zeros((5,7))
print(matriz_de_zeros)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [17]:
#Exemplo de manipulacao de Arrays do numpy
notas_da_prova = [9.8, 7.7, 4.3, 5.4, 7.3]

array_de_notas = np.array(notas_da_prova)

#funcoes simples
print("maior nota" , array_de_notas.max())
print("menor nota",  array_de_notas.min())
print("desvio padrao", array_de_notas.std())
print("media", array_de_notas.mean())

#funcoes mais especificas
print("Posicao menor numero", array_de_notas.argmin())
print("Posicao maior numero", array_de_notas.argmax())

maior nota 9.8
menor nota 4.3
desvio padrao 1.9089263998384014
media 6.9
Posicao menor numero 2
Posicao maior numero 0


# Mascaras Booleanas

In [19]:
is_covid_positive = np.array(["Yes", "No", "Yes", "Yes", "No"])
print(is_covid_positive)

['Yes' 'No' 'Yes' 'Yes' 'No']


In [21]:
#Ao definir uma mascara booleana com uma condicao podemos ver quais dos itens atendem a essa condicao
mask = is_covid_positive == "Yes"
print(mask)

[ True False  True  True False]


In [23]:
#Isto pode ser muito util para filtrar dados dentro de uma array, tendo em vista que podemos buscar os itens que atendem a condicao
print(is_covid_positive[mask])

['Yes' 'Yes' 'Yes']


In [27]:
#A mascara tambem pode ser muito util para a edicao de itens que atendem a nossa condicao definida
is_covid_positive[mask] = "C19"
print(is_covid_positive)

['C19' 'No' 'C19' 'C19' 'No']


In [35]:
#A condicao de uma mascara tambem pode ser uma operacao matematica
media_dos_alunos = np.array([(9.8), 7.7, 8.3, 5.4, 6.8])
mask =  media_dos_alunos > 7
print(media_dos_alunos[mask])
print(mask)

[9.8 7.7 8.3]
[ True  True  True False False]


In [48]:
#Para filtrar os tipos de dados dentro de um item da array, podemos especificar o tipo de dados de cada valor do nosso item
alunos_e_resultados = np.array([("Joao", 9.8), ("Maria", 7.7), ("Pedro", 8.3), ("Vitoria", 5.4), ("Raissa", 6.8)], dtype = [("nome", "U10"), ("nota", "f4")])

#No dtype eu defini o primeiro elemento de cada item como um U10, onde U significa unicode string e o valor é o máximo de caracteres
#No segundo elemento o "f" representa um numero flutuante e o 4 é o numero de bytes que ocupará na memória

resultados = alunos_e_resultados["nota"]
mask_aprovados = resultados >= 7
alunos_aprovados = alunos_e_resultados[mask_aprovados]

mask_reprovados = ~mask_aprovados
alunos_reprovados = alunos_e_resultados[mask_reprovados]

print("Aprovados: ", alunos_aprovados)
print("Reprovados: ", alunos_reprovados)




Aprovados:  [('Joao', 9.8) ('Maria', 7.7) ('Pedro', 8.3)]
Reprovados:  [('Vitoria', 5.4) ('Raissa', 6.8)]
