In [5]:
import numpy as np

In [32]:
#lista generica em python
lista_de_numeros = [1 , 2, 3, 4, 5]
lista_de_numeros[1] = 3
print(lista_de_numeros)

#Array do numpy criada a partir da lista anterior
array_numpy = np.array(lista_de_numeros)
print(array_numpy)

[1, 3, 3, 4, 5]
[1 3 3 4 5]


In [33]:
#Apesar de ambos serem listas o python considera a Array do numpy um tipo distinto
print(type(lista_de_numeros))
print(type(array_numpy))

<class 'list'>
<class 'numpy.ndarray'>


In [19]:
#Funcao pronta do numpy para criar uma lista de zeros, onde a quantidade de numeros e usada como parametro 
lista_de_zeros = np.zeros(7)
print(Lista_de_zeros)

[0. 0. 0. 0. 0. 0. 0.]


In [25]:
#Matrizes
matriz_de_zeros = np.zeros((5,7))
print(matrizDeZeros)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [44]:
#Exemplo de manipulacao de Arrays do numpy
notas_da_prova = [9.8, 7.7, 4.3, 5.4, 7.3]

array_de_notas = np.array(notas_da_prova)

#funcoes simples
print("maior nota" , array_de_notas.max())
print("menor nota",  array_de_notas.min())
print("desvio padrao", array_de_notas.std())
print("media", array_de_notas.mean())

#funcoes mais especificas
print("Posicao menor numero", array_de_notas.argmin())
print("Posicao maior numero", array_de_notas.argmax())

maior nota 9.8
menor nota 4.3
desvio padrao 1.9089263998384014
media 6.9
Posicao menor numero 2
Posicao maior numero 0
